apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: main
  namespace: elk
spec:
  version: 7.10.0
  nodeSets:
    - name: master
      count: 3
      config:
        node.master: true
        node.data: false
        node.ingest: true
        node.store.allow_mmap: false
    - name: data
      count: 3
      config:
        node.master: false
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
  http:
    tls:
      selfSignedCertificate:
        disabled: true
