apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: main
  namespace: elk
spec:
  version: 7.10.0
  count: 2
  elasticsearchRef:
    name: main
  http:
    tls:
      selfSignedCertificate:
        disabled: true
