apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: main
  namespace: elk
  annotations:
    eck.k8s.elastic.co/license: basic
spec:
  version: 8.12.0
  nodeSets:
    - name: master
      count: 3
      config:
        node.roles:
          - master
          - ingest
        node.store.allow_mmap: false
    - name: data
      count: 3
      config:
        node.roles:
          - data
        node.store.allow_mmap: false
  http:
    tls:
      selfSignedCertificate:
        disabled: true
