apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: main
  namespace: elk
spec:
  version: 8.15.3
  count: 2
  elasticsearchRef:
    name: main
  config:
    server.publicBaseUrl: https://kb.elastic.sikademo.com
  http:
    tls:
      selfSignedCertificate:
        disabled: true
