version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      bootstrap.memory_lock: 'true'
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    environment:
      discovery.type: single-node
    ports:
      - 5601:5601
