filebeat.inputs:
  - type: stdin

output.elasticsearch:
  hosts:
    - 127.0.0.1:9200
  protocol: https
  username: elastic
  password: s13EzEM=pCaR9Fx_=N9X
  ssl.certificate_authorities:
    - ./ca.crt
