services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      bootstrap.memory_lock: 'true'
      xpack.security.enabled: 'false'
      xpack.security.enrollment.enabled: 'false'
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    environment:
      discovery.type: single-node
    ports:
      - 5601:5601
