filebeat.inputs:
  - type: stdin

output.elasticsearch:
  hosts:
    - 165.232.66.168:9200
    - 159.89.97.154:9200
    - 159.89.103.92:9200
  protocol: https
  username: elastic
  password: Li0GEipRkC2C6Sysy=NU
  ssl.certificate_authorities:
    - ./ca.crt
