apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: main
  namespace: elk
spec:
  version: 8.5.3
  count: 1
  elasticsearchRef:
    name: main
  http:
    tls:
      selfSignedCertificate:
        disabled: true
