apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: main
  namespace: elk
spec:
  version: 8.12.0
  count: 1
  elasticsearchRef:
    name: main
  config:
    server.publicBaseUrl: https://kb.k8s.sikademo.com
  http:
    tls:
      selfSignedCertificate:
        disabled: true
