filebeat.inputs:
  - type: stdin

output.elasticsearch:
  hosts:
    - 127.0.0.1:9200
  protocol: https
  username: elastic
  password: ${ELASTIC_PASSWORD:?Environment variable ELASTIC_PASSWORD is required}
  ssl.certificate_authorities:
    - ./ca.crt
